Compare_template: |
  [Role]
  당신은 대규모 언어 모델이 생성한 '비교·분석' 답변의 품질을 평가하는 전문가입니다.

  [reference_data]가 제공된다면 이를 **최우선 기준**으로 삼아 [응답 프롬프트]의 품질을 평가하세요.  
  reference_data가 없을 경우, 일반적으로 알려진 사실/지식에 기반해 평가하세요.

  [평가기준]
  다음 기준에 따라 각 항목을 0~10 범위에서 점수화하세요.  
  1. 비교 기준 명확성 (가중치 0.25) : 무엇을 기준으로 비교했는지 명확한가
  2. 균형성 (가중치 0.25) : 각 비교 대상이 공정하고 균형 있게 다루어졌는가
  3. 장단점 구분 (가중치 0.20) : 장점과 단점이 명확히 구분되어 있는가
  4. 분석 깊이 (가중치 0.15) : 단순 나열이 아니라 분석이 충분히 이루어졌는가
  5. 결론/추천 설득력 (가중치 0.15) : 최종 결론이나 추천이 합리적이고 설득력 있는가

  [총점 산출 방식]  
  - 각 항목의 점수를 0~10 사이 값으로 매기고, 가중치를 곱합니다.  
  - 모든 항목의 "(점수 × 가중치)" 합을 "(가중치 총합)"으로 나눕니다.  
  - 이 값을 다시 10으로 나누어 0~1 범위로 정규화합니다.  
  - 최종 총점은 **0~1 범위 소수점 2자리**로 표시하세요.  
  - 예: 총점 = (Σ(점수 × 가중치) / Σ(가중치)) / 10  
  
  [reference_data]
  {{reference_data}}

  [요청 프롬프트]
  {{prompt}}
  
  [응답 프롬프트]
  {{response}}
  
  [평가 결과]
  평가 결과는 반드시 아래와 같은 **JSON** 양식으로 제공해줘야 합니다.
  양식은 절대 변경하지 마세요.
  ```json
  {
    "비교 기준 명확성" : <0-10 점수>,
    "균형성" : <0-10 점수>,
    "장단점 구분" : <0-10 점수>,
    "분석 깊이" : <0-10 점수>,
    "결론·추천 설득력" : <0-10 점수>,
    "총점" : <0-1범위 소수점 2자리, 가중 평균>,
    "평가의견" : <brief reason summary>
  }
  ```