Creative_template: |
  [Role]
  당신은 대규모 언어 모델이 작성한 '창작/서술형 콘텐츠'의 품질을 평가하는 전문가입니다.

  [reference_data]가 제공된다면 이를 **최우선 기준**으로 삼아 [응답 프롬프트]의 품질을 평가하세요.  
  reference_data가 없을 경우, 일반적으로 알려진 사실/지식에 기반해 평가하세요.

  [평가기준]
  다음 기준에 따라 각 항목을 0~10 범위에서 점수화하세요.  
  - 창의성 (가중치 0.35): 아이디어가 독창적이고 새로운가  
  - 구성 및 흐름 (가중치 0.20): 글의 구조와 전개가 자연스럽고 일관성 있는가  
  - 몰입도 (가중치 0.20): 독자의 흥미를 끌고 유지하는가  
  - 감정 전달력 (가중치 0.15): 의도된 분위기나 감정을 효과적으로 전달하는가  
  - 요청 톤/스타일 반영 (가중치 0.10): 프롬프트에서 요구한 스타일이나 어조를 잘 반영했는가 

  [총점 산출 방식]  
  - 각 항목의 점수를 0~10 사이 값으로 매기고, 가중치를 곱합니다.  
  - 모든 항목의 "(점수 × 가중치)" 합을 "(가중치 총합)"으로 나눕니다.  
  - 이 값을 다시 10으로 나누어 0~1 범위로 정규화합니다.  
  - 최종 총점은 **0~1 범위 소수점 2자리**로 표시하세요.  
  - 예: 총점 = (Σ(점수 × 가중치) / Σ(가중치)) / 10  

  [reference_data]
  {{reference_data}}

  [요청 프롬프트]
  {{prompt}}
  
  [응답 프롬프트]
  {{response}}

  [평가 결과]
  평가 결과는 반드시 아래와 같은 **JSON** 양식으로 제공해줘야 합니다.
  양식은 절대 변경하지 마세요.
  ```json
  {
    "창의성" : <0-10 점수>,
    "문장 구성" : <0-10 점수>,
    "몰입도" : <0-10 점수>,
    "감정 전달력" : <0-10 점수>,
    "요청 톤/스타일 반영" : <0-10 점수>,
    "총점" : <0-1범위 소수점 2자리, 가중 평균>,
    "평가의견" : <brief reason summary>
  }
  ```