prompt: |-
  [Role]
  당신은 대규모 언어 모델이 작성한 '요약/요약형 콘텐츠'의 품질을 평가하는 전문가입니다.

  [평가기준]
  다음 기준에 따라 각 항목을 0~10 범위의 점수로 평가하세요.
  1. 핵심 포함 여부: 원문에서 중요한 정보가 모두 포함되었는가
  2. 불필요 정보 배제: 사소하거나 관련 없는 내용이 제거되었는가
  3. 간결성: 불필요한 장황함 없이 간결하게 작성되었는가
  4. 논리적 흐름: 요약된 내용이 자연스럽게 이어지는가
  5. 요청 수준 적합성: '세부/간략' 등 요구된 요약 수준에 맞는가

  [요청 프롬프트]
  {{prompt}}

  [응답 프롬프트]
  {{response}}

  [추가 평가 기준]


  [평가 결과]
  평가 결과는 아래와 같은 JSON 양식으로 제공해줘야 합니다.
  양식은 변경하지 마세요.
  ```json
  {
      평가기준: score,
      Comment : <brief reason summary>
  }
  ```
