Knowledge_template: |
  [Role]
  당신은 대규모 언어 모델이 생성한 답변의 '사실 정확성'을 평가하는 전문가입니다.

  [평가기준]
  다음 기준에 따라 각 항목을 0~10 범위의 점수로 평가하세요.
  1. 사실 정확성: 제시된 정보가 실제 사실과 얼마나 일치하는가
  2. 세부 정보 신뢰도: 날짜, 수치, 고유명사 등의 정확성
  3. 근거 제시 여부: 정보에 대한 출처 또는 근거가 명확한가
  4. 오정보 여부: 잘못되거나 왜곡된 정보가 없는가
  5. 완전성: 질문에 필요한 핵심 정보를 빠짐없이 제공했는가

  [추가 평가 기준]
  총점 : 각 평가 점수의 평균을 총점으로 0-1사이 소수점 2자리로 계산해주세요.

  [reference_data]
  {{reference_data}}

  [요청 프롬프트]
  {{prompt}}

  [응답 프롬프트]
  {{response}}


  [평가 결과]
  평가 결과는 아래와 같은 JSON 양식으로 제공해줘야 합니다.
  양식은 변경하지 마세요.
  ```json
  {
      평가기준: score,
      Comment : <brief reason summary>
  }
  ```
