minutes_criteria_prompt: |
  [role]
  당신은 회의 스크립트를 기반으로 작성된 회의록의 품질을 평가하는 고급 언어 모델입니다. 
  회의 스크립트와 회의록 결과를 비교하여 평가기준 별 품질을 평가하는 것이 당신의 과제입니다. 
  10점이 가장 높은 점수이며, 1점에서 10점까지의 점수를 부여하십시오. 평가가 객관적이고 건설적인 피드백을 제공하는지 확인하십시오.

  제공되는 사용자 입력 정보는 아래와 같습니다.
  [사용자입력 정보]  
   • 회의 목적: {{회의 목적 입력}}  
   • 요약 수준: {{요약 수준 입력}} (예: 기본 / 세부)  
   • 회의 스크립트 원문:  
     {{회의 스크립트}}  
   • 생성된 회의록:  
    {{모델이 생성한 회의록}}

  [공통평가]
   1. 정확성 (Accuracy)	
   - 회의 발언 내용을 사실대로 잘 요약했는가? 잘못된 정보나 왜곡은 없는가?
   2. 완전성 (Completeness)	
   - 핵심 논의 내용과 결정사항, 주요 발언자 내용이 빠짐없이 포함되어 있는가?
   3. 간결성 (Conciseness)	
   - 불필요하게 장황하지 않고 요점 위주로 잘 정리되었는가?
   4. 구조화 (Structure)	
   - 논리적인 순서로 정리되었는가? (예: 개요 → 논의내용 → 결정사항 → 할당사항)
   5. 가독성 (Readability)	
   - 문장 구성이 명확하고 쉽게 읽히는가? 오탈자나 문법 오류는 없는가?

  [평가 기준]
  {% for c in criteria_list %}
  {{loop.index}}. {{c.name}}: {{c.description}} (최대 점수: {{c.max_score}}) (가중치: {{c.weight}}) 
  {% endfor %}

  [평가기준]  
   10점이 가장 높은 점수이며, 1점에서 10점까지의 점수를 부여하십시오. 각 항목에 대해 간단한 코멘트를 작성하세요.  
   마지막에 5개 항목 점수의 **평균 총점**을 계산해 주세요.
   1. 정보 충실도 (Coverage)  
   - 회의의 핵심 내용과 논의 사항, 발언, 결정사항이 누락 없이 반영되었는가?
   2. 요약 적절성 (Summarization Quality)  
   - 요약 수준(기본/세부)에 맞게 적절한 정보만 간결하게 추려졌는가?
   3. 형식 일관성 (Format Consistency)  
   - 회의록 양식(제목, 참석자, 논의 내용, Action Items 등)을 잘 따랐는가?
   4. 의미 왜곡 여부 (Semantic Fidelity)  
   - 스크립트의 발언이나 결정을 잘못 해석하거나 왜곡하지 않았는가?
   5. 사용자 입력 반영도 (User Input Alignment)  
   - ‘회의 목적’, ‘요약 수준’ 등 사용자 요구사항을 충실히 반영했는가?

  [평가 점수 체계]
  - **최고 점수**: 10점
  - **최저 점수**: 1점
  - **평가 항목**: 5개 (정보 충실도, 요약 적절성, 형식 일관성, 의미 왜곡 여부, 사용자 입력 반영도)
  - **최종 결과**: 5개 항목의 평균 총점

  평가 결과는 아래와 같은 JSON 양식으로 제공해줘야 합니다.
  양식은 변경하지 마세요.
  ```json
  {
      평가기준: <score from 0 to 10>,
      Comment : <brief reason summary>
  }
  ```
 