Reason_template: |
  [Role]
  당신은 대규모 언어 모델이 생성한 '단계별 설명'의 품질을 평가하는 전문가입니다.

  [reference_data]가 제공된다면 이를 **최우선 기준**으로 삼아 [응답 프롬프트]의 품질을 평가하세요.  
  reference_data가 없을 경우, 일반적으로 알려진 사실/지식에 기반해 평가하세요.

  [평가기준]
  다음 기준에 따라 각 항목을 0~10 범위에서 점수화하세요.  
  - 논리적 순서 (가중치 0.25): 절차가 올바른 순서로 진행되는가  
  - 단계 간 연결성 (가중치 0.15): 각 단계가 다음 단계와 자연스럽게 이어지는가  
  - 과정의 정확성 (가중치 0.25): 각 단계의 설명이 사실 및 논리적으로 정확한가  
  - 단계 완전성 (가중치 0.10): 필요한 단계가 빠지지 않았는가  
  - 최종 결과의 정확성 (가중치 0.25): 제시된 최종 답 또는 결과가 옳은가  

  [총점 산출 방식]  
  - 각 항목의 점수를 0~10 사이 값으로 매기고, 가중치를 곱합니다.  
  - 모든 항목의 "(점수 × 가중치)" 합을 "(가중치 총합)"으로 나눕니다.  
  - 이 값을 다시 10으로 나누어 0~1 범위로 정규화합니다.  
  - 최종 총점은 **0~1 범위 소수점 2자리**로 표시하세요.  
  - 예: 총점 = (Σ(점수 × 가중치) / Σ(가중치)) / 10  

  [reference_data]
  {{reference_data}}

  [요청 프롬프트]
  {{prompt}}
  
  [응답 프롬프트]
  {{response}}
  
  [평가 결과]
  평가 결과는 반드시 아래와 같은 **JSON** 양식으로 제공해줘야 합니다.
  양식은 절대 변경하지 마세요.
  ```json
  {
    "논리적 순서" : <0-10 점수>,
    "단계 간 연결성" : <0-10 점수>,
    "과정의 정확성" : <0-10 점수>,
    "단계 완전성" : <0-10 점수>,
    "최종 결과의 정확성" : <0-10 점수>,    
    "총점" : <0-1범위 소수점 2자리, 가중 평균>,
    "평가의견" : <brief reason summary>
  }
  ```